# Generated by Django 4.1.5 on 2023-01-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, verbose_name="管理员用户名")),
                (
                    "realname",
                    models.CharField(default="", max_length=50, verbose_name="管理员姓名"),
                ),
                ("password", models.CharField(max_length=32, verbose_name="管理员密码")),
                ("gender", models.SmallIntegerField(default=1, verbose_name="性别")),
                ("status", models.SmallIntegerField(default=1, verbose_name="状态")),
                (
                    "addtime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="加入时间"),
                ),
                (
                    "updatetime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="更新时间"),
                ),
                (
                    "email",
                    models.EmailField(default="", max_length=254, verbose_name="邮箱"),
                ),
            ],
            options={"verbose_name": "管理员列表", "verbose_name_plural": "管理员列表",},
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, verbose_name="教师用户名")),
                (
                    "realname",
                    models.CharField(default="", max_length=50, verbose_name="教师姓名"),
                ),
                ("password", models.CharField(max_length=32, verbose_name="教师密码")),
                ("gender", models.SmallIntegerField(default=1, verbose_name="性别")),
                ("status", models.SmallIntegerField(default=1, verbose_name="状态")),
                (
                    "addtime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="加入时间"),
                ),
                (
                    "updatetime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="更新时间"),
                ),
                (
                    "email",
                    models.EmailField(default="", max_length=254, verbose_name="邮箱"),
                ),
            ],
            options={"verbose_name": "教师列表", "verbose_name_plural": "教师列表",},
        ),
    ]
