# Generated by Django 4.1.5 on 2023-02-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_id", models.IntegerField(default=0, verbose_name="报送人")),
                (
                    "name",
                    models.CharField(
                        default="", max_length=255, verbose_name="专利、行业标准名称"
                    ),
                ),
                (
                    "type",
                    models.CharField(default="", max_length=100, verbose_name="类型"),
                ),
                (
                    "posttime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="申请时间"),
                ),
                (
                    "gettime",
                    models.FloatField(
                        default=0.0, max_length=30, verbose_name="授权、发布时间"
                    ),
                ),
                (
                    "college",
                    models.CharField(default="", max_length=100, verbose_name="学院"),
                ),
                ("status", models.SmallIntegerField(default=1, verbose_name="状态")),
                (
                    "evidence",
                    models.CharField(default="", max_length=255, verbose_name="佐证材料"),
                ),
                (
                    "syear",
                    models.CharField(default="", max_length=255, verbose_name="归属学年"),
                ),
                (
                    "addtime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="加入时间"),
                ),
                (
                    "updatetime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="更新时间"),
                ),
            ],
            options={"verbose_name": "专业成果表", "verbose_name_plural": "专业成果表",},
        ),
        migrations.CreateModel(
            name="Appointed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_id", models.IntegerField(default=0, verbose_name="教师")),
                (
                    "name",
                    models.CharField(default="", max_length=255, verbose_name="聘任职称"),
                ),
                (
                    "gettime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="聘任日期"),
                ),
                ("status", models.SmallIntegerField(default=1, verbose_name="状态")),
                (
                    "addtime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="加入时间"),
                ),
                (
                    "updatetime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="更新时间"),
                ),
            ],
            options={"verbose_name": "评聘记录表", "verbose_name_plural": "评聘记录表",},
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.IntegerField(default=0, verbose_name="所属项目")),
                (
                    "name",
                    models.CharField(default="", max_length=255, verbose_name="论文名称"),
                ),
                (
                    "author",
                    models.CharField(default="", max_length=100, verbose_name="作者"),
                ),
                (
                    "college",
                    models.CharField(default="", max_length=100, verbose_name="学院"),
                ),
                (
                    "periodicals",
                    models.CharField(default="", max_length=255, verbose_name="论文期刊名称"),
                ),
                (
                    "rollno",
                    models.CharField(default="", max_length=255, verbose_name="卷号页码"),
                ),
                (
                    "ph",
                    models.CharField(default="", max_length=255, verbose_name="出版社"),
                ),
                (
                    "syear",
                    models.CharField(default="", max_length=255, verbose_name="归属学年"),
                ),
                (
                    "collection",
                    models.CharField(default="", max_length=255, verbose_name="论文收录情况"),
                ),
                ("status", models.SmallIntegerField(default=1, verbose_name="状态")),
                (
                    "evidence",
                    models.CharField(default="", max_length=255, verbose_name="佐证材料"),
                ),
                (
                    "addtime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="加入时间"),
                ),
                (
                    "updatetime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="更新时间"),
                ),
            ],
            options={"verbose_name": "学术论文表", "verbose_name_plural": "学术论文表",},
        ),
        migrations.CreateModel(
            name="Awards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_id", models.IntegerField(default=0, verbose_name="所属教师")),
                (
                    "name",
                    models.CharField(default="", max_length=255, verbose_name="名称"),
                ),
                (
                    "result",
                    models.CharField(default="", max_length=255, verbose_name="获奖成果名称"),
                ),
                (
                    "type",
                    models.CharField(default="", max_length=100, verbose_name="奖项等级"),
                ),
                (
                    "unit",
                    models.CharField(default="", max_length=100, verbose_name="主办单位"),
                ),
                (
                    "gettime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="获奖时间"),
                ),
                (
                    "college",
                    models.CharField(default="", max_length=100, verbose_name="学院"),
                ),
                ("status", models.SmallIntegerField(default=1, verbose_name="状态")),
                (
                    "evidence",
                    models.CharField(default="", max_length=255, verbose_name="佐证材料"),
                ),
                (
                    "syear",
                    models.CharField(default="", max_length=255, verbose_name="归属学年"),
                ),
                (
                    "addtime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="加入时间"),
                ),
                (
                    "updatetime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="更新时间"),
                ),
            ],
            options={"verbose_name": "获奖情况表", "verbose_name_plural": "获奖情况表",},
        ),
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.IntegerField(default=0, verbose_name="所属项目")),
                (
                    "name",
                    models.CharField(default="", max_length=255, verbose_name="论文名称"),
                ),
                (
                    "author",
                    models.CharField(default="", max_length=100, verbose_name="作者"),
                ),
                (
                    "editor",
                    models.CharField(default="", max_length=100, verbose_name="主、副、参编"),
                ),
                (
                    "words",
                    models.FloatField(default=0.0, max_length=30, verbose_name="字数"),
                ),
                (
                    "college",
                    models.CharField(default="", max_length=100, verbose_name="学院"),
                ),
                (
                    "syear",
                    models.CharField(default="", max_length=255, verbose_name="归属学年"),
                ),
                ("status", models.SmallIntegerField(default=1, verbose_name="状态")),
                (
                    "evidence",
                    models.CharField(default="", max_length=255, verbose_name="佐证材料"),
                ),
                (
                    "uptime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="出版时间"),
                ),
                (
                    "addtime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="加入时间"),
                ),
                (
                    "updatetime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="更新时间"),
                ),
            ],
            options={"verbose_name": "学术著作表", "verbose_name_plural": "学术著作表",},
        ),
        migrations.CreateModel(
            name="Face",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=50, verbose_name="名称"),
                ),
                ("status", models.SmallIntegerField(default=1, verbose_name="状态")),
                (
                    "addtime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="加入时间"),
                ),
                (
                    "updatetime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="更新时间"),
                ),
            ],
            options={"verbose_name": "政治面貌表", "verbose_name_plural": "政治面貌表",},
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=50, verbose_name="名称"),
                ),
                ("status", models.SmallIntegerField(default=1, verbose_name="状态")),
                (
                    "addtime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="加入时间"),
                ),
                (
                    "updatetime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="更新时间"),
                ),
            ],
            options={"verbose_name": "专业表", "verbose_name_plural": "专业表",},
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orders",
                    models.CharField(default="", max_length=50, verbose_name="项目编号"),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=50, verbose_name="项目名称"),
                ),
                (
                    "college",
                    models.CharField(default="", max_length=50, verbose_name="学院"),
                ),
                (
                    "principal",
                    models.CharField(default="", max_length=255, verbose_name="负责人编号"),
                ),
                (
                    "participant",
                    models.CharField(default="", max_length=255, verbose_name="参与人编号"),
                ),
                ("status", models.SmallIntegerField(default=1, verbose_name="状态")),
                (
                    "starttime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="立项时间"),
                ),
                (
                    "schoolyear",
                    models.CharField(default=0.0, max_length=100, verbose_name="学年"),
                ),
                (
                    "money",
                    models.FloatField(default=0.0, max_length=30, verbose_name="经费"),
                ),
                (
                    "sources",
                    models.FloatField(default=0.0, max_length=30, verbose_name="经费来源"),
                ),
                (
                    "oano",
                    models.FloatField(default=0.0, max_length=30, verbose_name="发文号"),
                ),
                (
                    "fsno",
                    models.FloatField(
                        default=0.0, max_length=30, verbose_name="财务系统编号"
                    ),
                ),
                (
                    "conclusion",
                    models.FloatField(default=0.0, max_length=30, verbose_name="结题情况"),
                ),
                (
                    "addtime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="加入时间"),
                ),
                (
                    "updatetime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="更新时间"),
                ),
            ],
            options={"verbose_name": "项目表", "verbose_name_plural": "项目表",},
        ),
        migrations.CreateModel(
            name="SchoolYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=50, verbose_name="名称"),
                ),
                ("status", models.SmallIntegerField(default=1, verbose_name="状态")),
                (
                    "addtime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="加入时间"),
                ),
                (
                    "updatetime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="更新时间"),
                ),
            ],
            options={"verbose_name": "学年表", "verbose_name_plural": "学年表",},
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=50, verbose_name="名称"),
                ),
                ("status", models.SmallIntegerField(default=1, verbose_name="状态")),
                (
                    "addtime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="加入时间"),
                ),
                (
                    "updatetime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="更新时间"),
                ),
            ],
            options={"verbose_name": "职称表", "verbose_name_plural": "职称表",},
        ),
        migrations.AddField(
            model_name="teacher", name="face_id", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teacher",
            name="jointime",
            field=models.FloatField(default=0.0, max_length=30, verbose_name="入职时间"),
        ),
        migrations.AddField(
            model_name="teacher", name="major_id", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teacher",
            name="orders",
            field=models.CharField(default="", max_length=100, verbose_name="教师工号"),
        ),
        migrations.AddField(
            model_name="teacher", name="title_id", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="admin",
            name="password",
            field=models.CharField(default="", max_length=32, verbose_name="管理员密码"),
        ),
        migrations.AlterField(
            model_name="admin",
            name="username",
            field=models.CharField(default="", max_length=50, verbose_name="管理员用户名"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="password",
            field=models.CharField(default="", max_length=32, verbose_name="教师密码"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="username",
            field=models.CharField(default="", max_length=50, verbose_name="教师用户名"),
        ),
    ]
