# Generated by Django 4.1.5 on 2023-02-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_achievements_appointed_article_awards_books_face_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="participant_score",
            field=models.CharField(default="", max_length=255, verbose_name="参与人得分"),
        ),
        migrations.AddField(
            model_name="project",
            name="principal_score",
            field=models.CharField(default="", max_length=255, verbose_name="负责人得分"),
        ),
    ]
