# Generated by Django 4.1.5 on 2023-02-01 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_project_participant_score_project_principal_score"),
    ]

    operations = [
        migrations.RemoveField(model_name="teacher", name="username",),
    ]
