# Generated by Django 4.1.5 on 2023-02-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_remove_teacher_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievements",
            name="gettime",
            field=models.CharField(default="", max_length=50, verbose_name="授权、发布时间"),
        ),
        migrations.AlterField(
            model_name="achievements",
            name="posttime",
            field=models.CharField(default="", max_length=50, verbose_name="申请时间"),
        ),
        migrations.AlterField(
            model_name="appointed",
            name="gettime",
            field=models.CharField(default="", max_length=50, verbose_name="聘任日期"),
        ),
        migrations.AlterField(
            model_name="awards",
            name="gettime",
            field=models.CharField(default="", max_length=50, verbose_name="获奖时间"),
        ),
        migrations.AlterField(
            model_name="books",
            name="uptime",
            field=models.CharField(default="", max_length=50, verbose_name="出版时间"),
        ),
        migrations.AlterField(
            model_name="project",
            name="starttime",
            field=models.CharField(default="", max_length=50, verbose_name="立项时间"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="jointime",
            field=models.CharField(default="", max_length=50, verbose_name="入职时间"),
        ),
    ]
