# Generated by Django 4.1.5 on 2023-02-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_alter_achievements_gettime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="teacher_id",
            field=models.IntegerField(default=0, verbose_name="所属教师"),
        ),
        migrations.AddField(
            model_name="books",
            name="teacher_id",
            field=models.IntegerField(default=0, verbose_name="所属教师"),
        ),
    ]
