# Generated by Django 4.1.5 on 2023-02-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_article_teacher_id_books_teacher_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="endtime",
            field=models.CharField(default="", max_length=50, verbose_name="结项时间"),
        ),
    ]
