# Generated by Django 4.1.5 on 2023-02-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_joinproject_remove_project_participant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="conclusion",
            field=models.CharField(default="", max_length=255, verbose_name="结题情况"),
        ),
        migrations.AlterField(
            model_name="project",
            name="fsno",
            field=models.CharField(default="", max_length=255, verbose_name="财务系统编号"),
        ),
        migrations.AlterField(
            model_name="project",
            name="oano",
            field=models.CharField(default="", max_length=255, verbose_name="发文号"),
        ),
        migrations.AlterField(
            model_name="project",
            name="sources",
            field=models.CharField(default="", max_length=255, verbose_name="经费来源"),
        ),
    ]
