# Generated by Django 4.1.5 on 2023-02-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0010_project_joins"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="principal",
            field=models.CharField(default="", max_length=255, verbose_name="负责人"),
        ),
    ]
