# Generated by Django 4.1.7 on 2023-03-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_project_principal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor_id", models.IntegerField(default=0, verbose_name="所属医生")),
                ("user_id", models.IntegerField(default=0, verbose_name="所属用户")),
                ("status", models.SmallIntegerField(default=1, verbose_name="状态")),
                (
                    "app_date",
                    models.CharField(default="", max_length=255, verbose_name="预约日期"),
                ),
                (
                    "start_time",
                    models.FloatField(default=0.0, max_length=30, verbose_name="预约时间"),
                ),
                (
                    "end_time",
                    models.FloatField(default=0.0, max_length=30, verbose_name="预约时间"),
                ),
                (
                    "addtime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="加入时间"),
                ),
                (
                    "updatetime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="更新时间"),
                ),
            ],
            options={"verbose_name": "预约表", "verbose_name_plural": "预约表",},
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orders",
                    models.CharField(default="", max_length=100, verbose_name="医生工号"),
                ),
                (
                    "realname",
                    models.CharField(default="", max_length=50, verbose_name="姓名"),
                ),
                (
                    "password",
                    models.CharField(default="", max_length=32, verbose_name="密码"),
                ),
                (
                    "telephone",
                    models.CharField(default="", max_length=50, verbose_name="电话"),
                ),
                ("gender", models.SmallIntegerField(default=1, verbose_name="性别")),
                (
                    "avatar",
                    models.CharField(default="", max_length=255, verbose_name="头像"),
                ),
                ("status", models.SmallIntegerField(default=1, verbose_name="状态")),
                (
                    "addtime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="加入时间"),
                ),
                (
                    "updatetime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="更新时间"),
                ),
                (
                    "email",
                    models.EmailField(default="", max_length=254, verbose_name="邮箱"),
                ),
            ],
            options={"verbose_name": "医生表", "verbose_name_plural": "医生表",},
        ),
        migrations.CreateModel(
            name="Reports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor_id", models.IntegerField(default=0, verbose_name="所属医生")),
                ("user_id", models.IntegerField(default=0, verbose_name="所属用户")),
                ("appointment_id", models.IntegerField(default=0, verbose_name="所属预约")),
                ("status", models.SmallIntegerField(default=1, verbose_name="状态")),
                (
                    "symptoms",
                    models.CharField(default="", max_length=255, verbose_name="症状"),
                ),
                (
                    "results",
                    models.CharField(default="", max_length=255, verbose_name="结果"),
                ),
                (
                    "treatment",
                    models.CharField(default="", max_length=255, verbose_name="治疗方案"),
                ),
                (
                    "desc",
                    models.CharField(default="", max_length=255, verbose_name="说明"),
                ),
                (
                    "addtime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="加入时间"),
                ),
                (
                    "updatetime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="更新时间"),
                ),
            ],
            options={"verbose_name": "报告表", "verbose_name_plural": "报告表",},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(default="", max_length=50, verbose_name="姓名"),
                ),
                (
                    "password",
                    models.CharField(default="", max_length=32, verbose_name="密码"),
                ),
                ("gender", models.SmallIntegerField(default=1, verbose_name="性别")),
                ("age", models.IntegerField(default=0, verbose_name="年龄")),
                (
                    "avatar",
                    models.CharField(default="", max_length=255, verbose_name="头像"),
                ),
                (
                    "address",
                    models.CharField(default="", max_length=255, verbose_name="地址"),
                ),
                ("status", models.SmallIntegerField(default=1, verbose_name="状态")),
                (
                    "addtime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="加入时间"),
                ),
                (
                    "updatetime",
                    models.FloatField(default=0.0, max_length=30, verbose_name="更新时间"),
                ),
                (
                    "email",
                    models.EmailField(default="", max_length=254, verbose_name="邮箱"),
                ),
                (
                    "telephone",
                    models.CharField(default="", max_length=20, verbose_name="电话"),
                ),
            ],
            options={"verbose_name": "用户表", "verbose_name_plural": "用户表",},
        ),
        migrations.DeleteModel(name="Achievements",),
        migrations.DeleteModel(name="Appointed",),
        migrations.DeleteModel(name="Article",),
        migrations.DeleteModel(name="Awards",),
        migrations.DeleteModel(name="Books",),
        migrations.DeleteModel(name="Face",),
        migrations.DeleteModel(name="JoinProject",),
        migrations.DeleteModel(name="Major",),
        migrations.DeleteModel(name="Project",),
        migrations.DeleteModel(name="SchoolYear",),
        migrations.DeleteModel(name="Teacher",),
        migrations.DeleteModel(name="Title",),
    ]
