# Generated by Django 4.1.7 on 2023-03-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0014_doctor_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="comments",
            field=models.CharField(default="", max_length=255, verbose_name="备注"),
        ),
    ]
