# Generated by Django 4.1.7 on 2023-03-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0016_alter_appointment_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.IntegerField(default=1, verbose_name="状态"),
        ),
    ]
