# Generated by Django 3.2.13 on 2023-03-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='realname',
            field=models.CharField(default='', max_length=50, verbose_name='RealName'),
        ),
    ]
