# Generated by Django 4.1.7 on 2023-03-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0018_user_realname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="end_time",
        ),
    ]
