# Generated by Django 3.0.5 on 2020-04-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=8)),
                ('telephone', models.CharField(default='', max_length=20)),
                ('addtime', models.FloatField(default=0.0, max_length=30)),
                ('updatetime', models.FloatField(default=0.0, max_length=30)),
                ('address', models.CharField(default='', max_length=255)),
                ('sex', models.SmallIntegerField(default=0)),
                ('status', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
