# Generated by Django 3.0.5 on 2020-04-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20200421_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avator',
            field=models.CharField(default='', max_length=255),
        ),
    ]
