# Generated by Django 3.0.5 on 2020-04-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20200421_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='posts_id',
            field=models.IntegerField(default=0),
        ),
    ]
