# Generated by Django 3.0.5 on 2020-04-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_message_posts_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Touch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('message_id', models.IntegerField(default=0)),
                ('status', models.SmallIntegerField(default=1)),
                ('addtime', models.FloatField(default=0.0, max_length=30)),
            ],
        ),
    ]
