# Generated by Django 3.0.5 on 2020-04-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_touch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('status', models.SmallIntegerField(default=1)),
                ('addtime', models.FloatField(default=0.0, max_length=30)),
            ],
        ),
    ]
