# Generated by Django 3.0.5 on 2020-04-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_signs'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_del',
            field=models.SmallIntegerField(default=0),
        ),
    ]
