# Generated by Django 4.1.7 on 2023-03-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0011_message_is_del"),
    ]

    operations = [
        migrations.DeleteModel(name="Message",),
        migrations.DeleteModel(name="Score",),
        migrations.DeleteModel(name="Signs",),
        migrations.DeleteModel(name="Touch",),
        migrations.DeleteModel(name="User",),
    ]
